version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
  ApplicationStart:
    - location: scripts/run.sh
      timeout: 100
      runas: ubuntu
    - location: scripts/healthcheck.sh
      timeout: 100
      runas: ubuntu
    - location: scripts/switch.sh
      timeout: 100
      runas: ubuntu