version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  # 배포 시 실행될 파일, deploy.sh는 배포파일을 우분투 내에 실행시켜줌
  AfterInstall:
    # location은 프로젝트의 root경로 기준
    - location: stop.sh
      timeout: 60
      runas: ubuntu

  ApplicationStart:
    - location: start.sh
      timeout: 60
      runas: ubuntu